AIDE_CONFIG_FILE = attribute(
                             'aide_config_file',
                             default: '/etc/aide.conf',
                             description: "The location for your aide.conf confi
g file on the filesystem"
)
AIDE_CONFIG_FILE_PERMS = attribute(
                                   'aide_config_file_perms',
                                   default: 0o600,
                                   description: "The permissions of the aide.con
f config file"
)
AIDE_RULE_LINES = attribute(
                            'aide_rule_lines',
                            default: ['Generated by Chef for ',
                                      '^FIPSR\s*='],
                            description: "The expressions matching lines that should be in the aide configuration file"
)

# RHEL6: 1.4.1, 1.4.2
# CENTOS6: 1.3.1, 1.3.2
# UBUNTU: 8.3.1, 8.3.2

describe package('aide') do
  it { should be_installed }
end

# CENTOS6: 1.3.2
if %w(rhel fedora centos redhat).include?(os[:family])
  describe file(AIDE_CONFIG_FILE) do
    it { should be_file }
    it { should exist }

    it { should be_owned_by 'root' }
    it { should be_grouped_into 'root' }
    its(:mode) { should cmp AIDE_CONFIG_FILE_PERMS }
  end

  AIDE_RULE_LINES.each do |line|
    describe file(AIDE_CONFIG_FILE) do
      its(:content) { should match(%r{#{line}}m) }
    end
  end

  describe file('/var/lib/aide/aide.db.gz') do
    it { should be_file }
    it { should be_owned_by 'root' }
  end

  describe crontab('root').commands('/usr/sbin/aide --check')  do
    its('minutes') { should cmp 0 }
    its('hours') { should cmp 5 }
    its('days') { should cmp '*' }
    its('months') { should cmp '*' }
    its('weekdays') { should cmp '*' }
  end
end

# UBUNTU: 8.3.2
if %w(ubuntu debian).include?(os[:family])
  describe crontab('root').commands('/usr/bin/aide --check')  do
    its('minutes') { should cmp 0 }
    its('hours') { should cmp 5 }
    its('days') { should cmp '*' }
    its('months') { should cmp '*' }
    its('weekdays') { should cmp '*' }
  end
end
